Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CoreProjeUI.Controllers
{
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMedia());

        public IActionResult Index()
        {
            var values = socialMediaManager.GetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia socialMedia)
        {
            socialMedia.Status = true;
            socialMediaManager.TAdd(socialMedia);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSocialMedia(int id)
        {
            var values = socialMediaManager.TGetById(id);
            socialMediaManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSocialMedia(int id)
        {
            var values = socialMediaManager.TGetById(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia socialMedia)
        {
            socialMediaManager.TUpdate(socialMedia);
            return RedirectToAction("Index");
        }
    }
}

Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "AddSocialMedia";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yeni Hesap Ekleme Paneli</h3>
</div>
@using (Html.BeginForm("AddSocialMedia", "SocialMedia", FormMethod.Post))
{
    <br />
    @Html.Label("Başlığı")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <label>Url</label>
    @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
    <br />
    <label>İkon</label>
    @Html.TextBoxFor(x => x.Icon, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>
    <button class="btn btn-outline-dark">İptal</button>

}

Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "EditExperience";
}

<div class="card-header border-0">
    <h3 class="mb-0">Hesap Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditSocialMedia", "SocialMedia", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SocialMediaID)
    <br />
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <label>Url</label>
    @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
    <br />
    <label>İkon</label>
    @Html.TextBoxFor(x => x.Icon, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
}

Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="card-header bg-transparent border-0">
                    <h3 class="text-white mb-0">Sosyal Medya Hesapları</h3>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-dark table-flush">
                        <thead class="thead-dark">
                            <tr>
                                <th>#</th>
                                <th>Başlık</th>
                                <th>Sil</th>
                                <th>Güncelle</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.SocialMediaID</td>
                                    <td>@item.Name</td>
                                    <td><a href="/SocialMedia/DeleteSocialMedia/@item.SocialMediaID" class="btn btn-outline-danger">Sil</a></td>
                                    <td><a href="/SocialMedia/EditSocialMedia/@item.SocialMediaID" class="btn btn-outline-success">Güncelle</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <a href="/SocialMedia/AddSocialMedia" class="btn btn-outline-primary">Yeni Hesap Ekle</a>
            </div>
        </div>
    </div>
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>