Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CoreProjeUI.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkill());

        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenek Listesi";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listesi";

            var values = skillManager.GetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Yetenek Ekleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }

        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
            var values = skillManager.TGetById(id);
            skillManager.TDelete(values);
            return RedirectToAction ("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Yetenek Güncelleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Güncelleme";

            var values = skillManager.TGetById(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

Views/Skill/AddSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "AddSkill";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Ekleme Sayfası</h3>
</div>
<form class="form-group" method="post">
    <br />
    @Html.Label("Yetenek Başlığı")
    <input type="text" name="Title" class="form-control" />
    <br />
    <label>Değer</label>
    <input type="text" name="Value" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>
</form>

Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "EditSkill";
}

<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Düzenleme Sayfası</h3>
</div>
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
        @Html.HiddenFor(x => x.SkillID)
    <br />
    @Html.Label("Yetenek Başlığı")
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    <label>Değer</label>
    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
}

Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "Index";
}


<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi Tablosu</h3>
</div>
<div class="table-responsive">
    <table class="table align-items-center table-flush">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="sort" data-sort="name">#</th>
                <th scope="col" class="sort" data-sort="budget">Başlık</th>
                <th scope="col" class="sort" data-sort="status">Oran</th>
                <th scope="col">Sil</th>
                <th scope="col" class="sort" data-sort="completion">Güncelle</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody class="list">
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @item.SkillID
                    </th>
                    <td class="budget">
                        @item.Title
                    </td>
                    <td>
                        <div class="d-flex align-items-center">
                            <span class="completion mr-2">@item.Value %</span>
                            <div>
                                <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-outline-danger">Sil</a></td>
                    <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-outline-success">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
    <a href="/Skill/AddSkill" class="btn btn-outline-primary">Yeni Yetenek Ekle</a>
    <br />
</div>
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>