Controllers/ContactSubplaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CoreProjeUI.Controllers
{
    public class ContactSubplaceController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContact());

        [HttpGet]
        public IActionResult Index()
        {
            var values = contactManager.TGetById(1);
            return View(values);
        }

        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            contactManager.TUpdate(contact);
            return RedirectToAction("Index", "Default");
        }
    }
}

Views/ContactSubplace/Index.cshtml
@model EntityLayer.Concrete.Contact
@{
    Layout = "/Views/Shared/_NewAdminLayout.cshtml";
    ViewData["Title"] = "Index";
}

<div class="card-header border-0">
    <h3 class="mb-0">Alt İletişim Bilgileri Düzenleme Paneli</h3>
</div>

@using (Html.BeginForm("Index", "ContactSubplace", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ContactID)
    <br />
    <label>Başlık</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    <label>Telefon</label>
    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
    <br />
    <label>Mail</label>
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />
    <label>Telefon</label>
    @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x => x.Description, 10, 2, new { @class = "form-control" })
    <br />
    <button class="btn btn-outline-success">Güncelle</button>
}
<script src="~/corona-free-dark-bootstrap-admin-template-1.0.0/template/assets/vendors/js/vendor.bundle.base.js"></script>